Soporte.TI.Web/Models/ErrorViewModel.cs
namespace Soporte.TI.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Soporte.TI.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Soporte.TI.Web.Models;
using System.Diagnostics;

namespace Soporte.TI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Soporte.TI.Web/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using SoporteTI.Application.DTOs;
using SoporteTI.Application.Helpers;
using SoporteTI.Application.Interfaces;
using System.Threading.Tasks;

namespace Soporte.TI.Web.Controllers
{
    public class TicketController : Controller
    {
        private readonly ITicketService _ticketService;
        public TicketController(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _ticketService.GetAllTicketAsync());
        }

        public async Task<IActionResult> Create()
        {
            TicketDto ticketDto = new TicketDto() { Tk_Folio = await _ticketService.GetLastTicketFolioAsync()};
            ViewBag.Status = EnumDropdownHelper.GetStatusTicket();
            ViewBag.Impact = EnumDropdownHelper.GetImpactTicket();
            ViewBag.Priority = EnumDropdownHelper.GetPriorityTicket();
            return View(ticketDto);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TicketDto ticketDto)
        {
            await _ticketService.CrearTicketAsync(ticketDto);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string Tk_Folio)
        {
            TicketDto ticket = await _ticketService.GetTicketByFolioAsync(Tk_Folio);
            ViewBag.Status = EnumDropdownHelper.GetStatusTicket();
            ViewBag.Impact = EnumDropdownHelper.GetImpactTicket();
            ViewBag.Priority = EnumDropdownHelper.GetPriorityTicket();
            return View(ticket);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TicketDto ticketDto)
        {
            await _ticketService.UpdateTicketAsync(ticketDto);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string Tk_Folio) 
        {
            TicketDto ticket = await _ticketService.GetTicketByFolioAsync(Tk_Folio);
            ViewBag.Status = EnumDropdownHelper.GetStatusTicket();
            ViewBag.Impact = EnumDropdownHelper.GetImpactTicket();
            ViewBag.Priority = EnumDropdownHelper.GetPriorityTicket();
            return View(ticket);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(TicketDto ticketDto)
        {
            await _ticketService.DeleteTicketAsync(ticketDto);
            return RedirectToAction("Index");
        }
    }
}

Soporte.TI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center row">
    <h1 class="display-4">Welcome</h1>
    <hr />
    <div class="col-lg-6">
        <p class="text-lg-start">A ticket system is important for the IT department and technical support because it helps manage all requests, problems, and issues in the company’s technology in an organized way. This system makes it easy to track each case and solve them on time. It also helps improve communication between the support team and the users, making sure each request gets the right attention based on its importance and difficulty. A ticket system helps record and understand repeated problems, which helps improve the service and prevent future issues. This not only makes the IT team more productive but also makes the users happy with fast and clear support.</p>
    </div>
    <div class="col-lg-6 mt-5">
        <a href="/Ticket/Create" class="btn btn-lg btn-primary">New Ticket</a>
        <a href="/Ticket/Index" class="btn btn-lg btn-info">Index</a>
    </div>
</div>

Soporte.TI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Soporte.TI.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Soporte.TI.Web.styles.css" asp-append-version="true" />
</head>
<body class="">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ticket Systems</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="Index">Ticket Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="Index">Ticket Management</a>
                        </li>                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Soporte.TI.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Soporte.TI.Web/Views/Ticket/Create.cshtml
@using SoporteTI.Application.Helpers
@model SoporteTI.Application.DTOs.TicketDto

@{
    ViewData["Title"] = "Crear";
}

<div class="card">
    <div class="card-body">

        <h1>New Ticket</h1>
        <div class="card">
            <div class="card-body">
                <p>
                    Please fill out the following form with the required information to create a new ticket.
                    <br />This will help us assign and manage your request efficiently.
                    <br />Make sure to enter all the relevant details so we can give you a quick and proper response.
                </p>
            </div>
        </div>
        
        <hr />

        <form asp-action="Create" class="row">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-lg-4">
                <label asp-for="Tk_Folio" class="control-label"></label>
                <input asp-for="Tk_Folio" class="form-control" readonly />
                <span asp-validation-for="Tk_Folio" class="text-danger"></span>
            </div>

            <div class="col-lg-12">
                <label asp-for="Tk_Title" class="control-label"></label>
                <input asp-for="Tk_Title" class="form-control" />
                <span asp-validation-for="Tk_Title" class="text-danger"></span>
            </div>
            <div class="col-lg-12">
                <label asp-for="Tk_Description" class="control-label"></label>
                <input asp-for="Tk_Description" class="form-control" />
                <span asp-validation-for="Tk_Description" class="text-danger"></span>
            </div>
            <div class="col-lg-12">
                <label asp-for="Tk_Reason" class="control-label"></label>
                <input asp-for="Tk_Reason" class="form-control" />
                <span asp-validation-for="Tk_Reason" class="text-danger"></span>
            </div>
            <div class="col-lg-4">
                <label asp-for="Tk_StatusId" class="control-label"></label>
                <select asp-for="Tk_StatusId" class="form-control" asp-items="@(new SelectList(ViewBag.Status, "Value", "Text",1))" disabled>
                </select>
                <span asp-validation-for="Tk_StatusId" class="text-danger"></span>
            </div>
            <div class="col-lg-4">
                <label asp-for="Tk_ImpactId" class="control-label"></label>
                <select asp-for="Tk_ImpactId" class="form-control" asp-items="@(new SelectList(ViewBag.Impact, "Value", "Text"))">
                    <option value="">Select an option</option>
                </select>
                <span asp-validation-for="Tk_ImpactId" class="text-danger"></span>
            </div>
            <div class="col-lg-4">
                <label asp-for="Tk_PriorityId" class="control-label"></label>
                <select asp-for="Tk_PriorityId" class="form-control" asp-items="@(new SelectList(ViewBag.Priority, "Value", "Text"))">
                    <option value="">Select an option</option>
                </select>
                <span asp-validation-for="Tk_PriorityId" class="text-danger"></span>
            </div>
            
            <div class="col-lg-12 mt-2">
                <hr />
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-controller="Home" asp-action="Index" class="btn btn-danger">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Soporte.TI.Web/Views/Ticket/Delete.cshtml
@using SoporteTI.Application.Helpers
@model SoporteTI.Application.DTOs.TicketDto

@{
    ViewData["Title"] = "Delete";
}

<div class="card">
    <div class="card-body">

        <h1 class="text-danger">Are you sure you want to delete this record?</h1>

        <div class="card mb-3">
            <div class="card-body">
                <p>
                    Please review the ticket information below before confirming the deletion.
                    <br />This action cannot be undone.
                </p>
            </div>
        </div>

        <hr />

        <form asp-action="DeleteConfirmed" class="row">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-lg-4">
                <label asp-for="Tk_Folio" class="control-label"></label>
                <input asp-for="Tk_Folio" class="form-control" readonly />
            </div>

            <div class="col-lg-12">
                <label asp-for="Tk_Title" class="control-label"></label>
                <input asp-for="Tk_Title" class="form-control" readonly />
            </div>

            <div class="col-lg-12">
                <label asp-for="Tk_Description" class="control-label"></label>
                <input asp-for="Tk_Description" class="form-control" readonly />
            </div>

            <div class="col-lg-12">
                <label asp-for="Tk_Reason" class="control-label"></label>
                <input asp-for="Tk_Reason" class="form-control" readonly />
            </div>

            <div class="col-lg-4">
                <label asp-for="Tk_StatusId" class="control-label"></label>
                <select asp-for="Tk_StatusId" class="form-control" asp-items="@(new SelectList(ViewBag.Status, "Value", "Text", Model.Tk_StatusId))" disabled>
                </select>
            </div>

            <div class="col-lg-4">
                <label asp-for="Tk_ImpactId" class="control-label"></label>
                <select asp-for="Tk_ImpactId" class="form-control" asp-items="@(new SelectList(ViewBag.Impact, "Value", "Text", Model.Tk_ImpactId))" disabled>
                </select>
            </div>

            <div class="col-lg-4">
                <label asp-for="Tk_PriorityId" class="control-label"></label>
                <select asp-for="Tk_PriorityId" class="form-control" asp-items="@(new SelectList(ViewBag.Priority, "Value", "Text", Model.Tk_PriorityId))" disabled>
                </select>
            </div>

            <div class="col-lg-12 mt-3">
                <hr />
                <input type="submit" value="Delete" class="btn btn-danger" />
                <a asp-controller="Home" asp-action="Index" class="btn btn-outline-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>

Soporte.TI.Web/Views/Ticket/Edit.cshtml
@model SoporteTI.Application.DTOs.TicketDto

@{
    ViewData["Title"] = "Edit";
}

<div class="card">
    <div class="card-body">

        <h1>Edit Ticket</h1>
        
        <hr />

        <form asp-action="Edit" class="row" method="post">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Tk_CreatedDate" />

            <div class="col-lg-4">
                <label asp-for="Tk_Folio" class="control-label"></label>
                <input asp-for="Tk_Folio" class="form-control" readonly />
                <span asp-validation-for="Tk_Folio" class="text-danger"></span>
            </div>

            <div class="col-lg-12">
                <label asp-for="Tk_Title" class="control-label"></label>
                <input asp-for="Tk_Title" class="form-control" />
                <span asp-validation-for="Tk_Title" class="text-danger"></span>
            </div>
            <div class="col-lg-12">
                <label asp-for="Tk_Description" class="control-label"></label>
                <input asp-for="Tk_Description" class="form-control" />
                <span asp-validation-for="Tk_Description" class="text-danger"></span>
            </div>
            <div class="col-lg-12">
                <label asp-for="Tk_Reason" class="control-label"></label>
                <input asp-for="Tk_Reason" class="form-control" />
                <span asp-validation-for="Tk_Reason" class="text-danger"></span>
            </div>
            <div class="col-lg-4">
                <label asp-for="Tk_StatusId" class="control-label"></label>
                <select asp-for="Tk_StatusId" class="form-control" asp-items="@(new SelectList(ViewBag.Status, "Value", "Text",1))" disabled>
                </select>
                <span asp-validation-for="Tk_StatusId" class="text-danger"></span>
            </div>
            <div class="col-lg-4">
                <label asp-for="Tk_ImpactId" class="control-label"></label>
                <select asp-for="Tk_ImpactId" class="form-control" asp-items="@(new SelectList(ViewBag.Impact, "Value", "Text"))">
                    <option value="">Select an option</option>
                </select>
                <span asp-validation-for="Tk_ImpactId" class="text-danger"></span>
            </div>
            <div class="col-lg-4">
                <label asp-for="Tk_PriorityId" class="control-label"></label>
                <select asp-for="Tk_PriorityId" class="form-control" asp-items="@(new SelectList(ViewBag.Priority, "Value", "Text"))">
                    <option value="">Select an option</option>
                </select>
                <span asp-validation-for="Tk_PriorityId" class="text-danger"></span>
            </div>
            
            <div class="col-lg-12 mt-2">
                <hr />
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Index" asp-controller="Ticket" asp-action="Index" class="btn btn-danger">Cancel</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Soporte.TI.Web/Views/Ticket/Index.cshtml
@using SoporteTI.Application.Helpers
@model IEnumerable<SoporteTI.Application.DTOs.TicketDto>


@{
    ViewData["Title"] = "Index";
}

<h1>
    Ticket Management

</h1>

<div class="col-12 mb-5">
<a asp-action="Create" class="btn btn-primary">Create New</a>
</div>
<div class="table table-responsive">
    <table class="table table-dark table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Tk_Folio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tk_Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tk_Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tk_Reason)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tk_CreatedById)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tk_AssignedToId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tk_StatusId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tk_CreatedDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tk_ImpactId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tk_PriorityId)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tk_Folio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tk_Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tk_Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tk_Reason)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tk_CreatedById)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tk_AssignedToId)
                    </td>
                    <td>
                        @EnumDropdownHelper.GetStatusTicketbyId(Convert.ToString(item.Tk_StatusId)).Text
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tk_CreatedDate)
                    </td>
                    <td>
                        @EnumDropdownHelper.GetImpactTicketbyId(Convert.ToString(item.Tk_ImpactId)).Text
                    </td>
                    <td>
                        @EnumDropdownHelper.GetPriorityTicketbyId(Convert.ToString(item.Tk_PriorityId)).Text
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { Tk_Folio = item.Tk_Folio }, new { @class = "btn btn-outline-warning" }) |
                        @* @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) | *@
                        @Html.ActionLink("Delete", "Delete", new { Tk_Folio = item.Tk_Folio }, new { @class = "btn btn-outline-danger" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>